name: Test

on:
  schedule:
    - cron: "30 20 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:     # Allows manual triggering

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # Required for FFmpeg installation
  API: ${{ secrets.API}}
  TOKEN: ${{ secrets.TOKEN}}
  GMAIL: ${{ secrets.GMAIL}}
  PASS: ${{ secrets.PASS}}

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test env vars for python
        run: TEST_SECRET=${{ secrets.API}}
        
      - name: WithOut
        run: python trans.py


      - name: With
        env:
          HTTP_PROXY: "https://0a5d-2405-201-6804-9152-1963-8355-74fd-525c.ngrok-free.app"
          HTTPS_PROXY: "https://0a5d-2405-201-6804-9152-1963-8355-74fd-525c.ngrok-free.app"
        run: python trans.py
